name: liveszczecin
description: LiveSzczecin App
publish_to: "none"

version: 2.0.4+9

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  better_player: ^0.0.63
  fluttertoast: ^8.2.2
  in_app_update: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: false
