name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "18"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Get keystore
        run: echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > "${{ github.workspace }}/keystore.jks"
      - name: Create keystore.properties file
        env:
          KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/android/key.properties
        run: |
          echo 'storeFile=${{ github.workspace }}/keystore.jks' > $KEYSTORE_PROPERTIES_PATH
          echo 'keyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'storePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
          echo 'keyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
      - name: Get dependencies
        run: flutter pub get
      - name: Build appbundle
        run: flutter build appbundle --release
      - name: Create release page
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/bundle/release/app-release.aab
          tag_name: ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false
